### PR TITLE
Adds Korean translation

### PR DESCRIPTION
**Pull request by MaronKB**

### CODE REVIEW

**Comment by PatrickBauer** [comment]
Thank you very much for your contribution, I'm gonna merge this probably later today. I'm always trying to give proper information  about the source of translation contributions. Could you take a look at https://github.com/anvil-vtt/FateX#translations and tell me if the translation is from some official source like an official Korean Fate Book? Or is there a public korean Fate SRD available?

**Comment by MaronKB** [comment]
it's from korean Fate core SRD: https://sites.google.com/site/fatecorekr/
and CCL is below:

> 페이트 코어 한국어 공개판은 Leonard Balsera, Brian Engard, Jeremy Keller, Ryan Macklin, Mike Olson, Clark Valentine, Amanda Valentine, Fred Hicks, Rob Donoghue가 개발, 저술, 편집한 Evil Hat Productions, LLC 제품 Fate Core System을 크리에이티브 커먼즈 저작자표시 3.0 Unported 라이선스에 의거하여 도서출판 초여명의 김성일이 번역한 작품입니다.
> 페이트 코어 한국어 공개판: https://sites.google.com/site/fatecorekr/ 은 크리에이티브 커먼즈 저작자표시 3.0 Unported (CC BY 3.0) 라이센스에 따라 이용할 수 있습니다.

**Comment by PatrickBauer** [comment]
Great, thank you!

**Comment by PatrickBauer** [comment]
Thank you very much for your contribution, its now integrated into the main branch.

**Pull request merged**
