### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by Pjb518**
This PR is mostly focused on standardising the naming convention used for CSS classes and simplifying the styling and templates throughout the system.

While the update is focused on the CSS and HTML, some changes will necessarily be made to the JS implementation wherever classes have been used as selectors.

~~**Note:** Since the new message cards have significant template changes, older messages will not be correctly styled. It doesn't have any meaningful impact on the end user other than the fact that they'll have some ugly messages in their chat history. It might be worth notifying users when they open the updated system for the first time, just so we don't get a pile of erroneous bug reports.~~

**Note:** We've instead decided to ship legacy chat message styles so that users don't end up with random unstyled messages in their chat history.

### CODE REVIEW

**Comment by Pjb518** [comment]
**TODO:** The sheet setup header was broken when the main sheet header was rewritten. Will probably tackle this this afternoon.

**Comment by Pjb518** [comment]
**TODO**

- Update the action buttons for section headings, aspects, and consequences to the new format.
- Add the increment and decrement buttons for skills to the new action button implementation.
- Remove all references to the old action buttons in the JS code once the remaining buttons have been updated.
- Extract the stress boxes to a new component that can be reused for consequences.
- Standardise the `desk` classes.

**Comment by Pjb518** [comment]
**TODO**

-  Fix the visual bug present in the main page sheet tabs when resizing the sheet. Should be a matter of increasing the size of the corner shapes so that the background never pokes through. See below:

image

- Fix the styles for the stunt range bar. Currently it looks like this:

image

It should look for like this:

image

**Review by PatrickBauer — APPROVED** [review]

**Comment by PatrickBauer** [comment]
Great work once again, thank you very much! ❤️

**Pull request merged**
