### PR TITLE
add Chinese translation files

### PR DESCRIPTION
**Pull request by Nowpaper**

### CODE REVIEW

**Comment by PatrickBauer** [comment]
Thank you very much, I'm gonna look at these next week. Thank you very much for your contribution! 🙂

**Comment by Nowpaper** [comment]
> Thank you very much, I'm gonna look at these next week. Thank you very much for your contribution! 🙂

You are welcome,I like the fate system so much and I want to promote it to friends but it seems that our English is not good, so we want this try to have a Chinese version :)

**Comment by Nowpaper** [comment]
I asked a professional to help proofread all the translated texts

**Review by PatrickBauer — APPROVED** [review]

**Comment by PatrickBauer** [comment]
@Nowpaper Sorry that it took so long, but: thank you very much! Your translation is now included in the newest release (0.9.0) 🥳

**Comment by PatrickBauer** [comment]
@Nowpaper 

I'm always trying to give proper information about the source of translation contributions. Could you take a look at https://github.com/anvil-vtt/FateX#translations and tell me if the translation is from some official source like an official Chinese Fate book? Or is there a public chinese Fate SRD available? 🙂

**Pull request merged**
